# =====================================================================
#          FILE: sdc_emitter.py
#
#   DESCRIPTION: Generates Synopsys Design Constraints (.sdc) from a
#                DigitalCircuit extracted by circuit_graph.py.  Detects
#                clock nets from pulse voltage sources and emits timing
#                constraints compatible with OpenROAD Flow Scripts.
#
#        AUTHOR: Juned Pinjari, juned.m.pinjari@gmail.com
#    MAINTAINED: Sumanto Kar, sumantokar@iitb.ac.in
#  ORGANIZATION: eSim Team at FOSSEE, IIT Bombay
#       CREATED: 2026-10-03
# =====================================================================

"""SDC constraint file emitter for eSim digital circuits.

Generates timing constraints for the OpenROAD flow:
- Real clock from ``pulse`` source → ``create_clock`` on the clock port
- Combinational-only (no clock) → ``create_clock -name virtual_clk``
- Default input/output delays relative to the clock
"""

# Default clock period (ns) when the netlist does not specify one
# or for virtual clocks on combinational-only circuits.
_DEFAULT_PERIOD_NS = 10.0


def _seconds_to_ns(value_seconds):
    """Convert a value in seconds to nanoseconds.

    eSim pulse parameters are in seconds (e.g. ``40`` for 40s in SPICE
    simulation time).  However, synthesis flows use nanoseconds.

    If the value is unreasonably large (> 1 second), it is likely
    expressed in raw SPICE simulation seconds and should be treated
    as a direct nanosecond value scaled by 1e9.
    """
    if value_seconds is None:
        return _DEFAULT_PERIOD_NS
    ns = value_seconds * 1e9
    if ns > 1e6:
        # Likely expressed in SPICE sim-time units, not SI seconds.
        # Fall back to a reasonable default.
        return _DEFAULT_PERIOD_NS
    return ns


def emit_sdc(circuit):
    """Generate an SDC constraints string from a DigitalCircuit.

    Parameters
    ----------
    circuit : circuit_graph.DigitalCircuit

    Returns
    -------
    str
        Complete SDC file content.
    """
    lines = []
    lines.append("# ──────────────────────────────────────────────────")
    lines.append(f"# SDC constraints for {circuit.module_name}")
    lines.append("# Auto-generated by eSim Netlist-to-RTL converter")
    lines.append("# ──────────────────────────────────────────────────")
    lines.append("")

    clock_name = "core_clk"

    if circuit.clock_net and circuit.clock_period is not None:
        # ── Real clock detected from pulse source ─────────────────
        period_ns = _seconds_to_ns(circuit.clock_period)
        lines.append(f"# Clock detected from pulse voltage source")
        lines.append(
            f"create_clock [get_ports {circuit.clock_net}]"
            f" -name {clock_name}"
            f" -period {period_ns:.2f}"
        )
    elif circuit.clock_net:
        # Clock port found but no period extracted
        lines.append(f"# Clock port detected but period unknown; "
                     f"using default {_DEFAULT_PERIOD_NS} ns")
        lines.append(
            f"create_clock [get_ports {circuit.clock_net}]"
            f" -name {clock_name}"
            f" -period {_DEFAULT_PERIOD_NS:.2f}"
        )
    else:
        # ── No clock: combinational-only circuit ──────────────────
        clock_name = "virtual_clk"
        lines.append("# No clock detected — combinational circuit.")
        lines.append("# Using a virtual clock for timing analysis.")
        lines.append(
            f"create_clock -name {clock_name}"
            f" -period {_DEFAULT_PERIOD_NS:.2f}"
        )

    lines.append("")

    # ── Input/output delays ───────────────────────────────────────
    # Use 20% of clock period as a conservative default delay.
    if circuit.clock_period is not None:
        delay = _seconds_to_ns(circuit.clock_period) * 0.2
    else:
        delay = _DEFAULT_PERIOD_NS * 0.2

    # Collect non-clock input port names
    input_ports = []
    output_ports = []
    for port in circuit.ports:
        if port.name == circuit.clock_net:
            continue  # don't constrain clock against itself
        if port.direction == "input":
            input_ports.append(port.name)
        elif port.direction == "output":
            output_ports.append(port.name)

    if input_ports:
        ports_str = " ".join(input_ports)
        lines.append(
            f"set_input_delay {delay:.2f}"
            f" -clock {clock_name}"
            f" [get_ports {{{ports_str}}}]"
        )

    if output_ports:
        ports_str = " ".join(output_ports)
        lines.append(
            f"set_output_delay {delay:.2f}"
            f" -clock {clock_name}"
            f" [get_ports {{{ports_str}}}]"
        )

    lines.append("")

    return "\n".join(lines)
